CREATE TABLE IF NOT EXISTS newsletter_issues(
id UUID PRIMARY KEY NOT NULL,
title TEXT NOT NULL,
text_content TEXT NOT NULL,
html_content TEXT NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
