CREATE TABLE IF NOT EXISTS "users" (
id UUID NOT NULL,
PRIMARY KEY (id),
"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"name" TEXT NOT NULL,
"email" TEXT UNIQUE NOT NULL,
"password_hash" TEXT NOT NULL,
"is_activated" BOOLEAN NOT NULL DEFAULT FALSE,
"is_subscribed" BOOLEAN NOT NULL DEFAULT FALSE,
"version" INTEGER NOT NULL DEFAULT 1
);


