CREATE TABLE IF NOT EXISTS users (
id UUID PRIMARY KEY NOT NULL,
user_name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
password_hash TEXT NOT NULL,
is_activated BOOLEAN NOT NULL DEFAULT FALSE,
is_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
is_admin BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
version INTEGER NOT NULL DEFAULT 1
);


