CREATE TABLE IF NOT EXISTS posts (
id UUID PRIMARY KEY NOT NULL,
title TEXT NOT NULL,
post_text TEXT NOT NULL,
img TEXT NOT NULL,
read_time INTEGER NOT NULL,
liked_by INTEGER[],
created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
version INTEGER NOT NULL DEFAULT 1
);
